### ISSUE TITLE
Can this be used with any autogressive model?

### ISSUE THREAD

**Issue by hello-fri-end** [jy-yuan/KIVI#1]
Hey @jy-yuan, thank you for the awesome paper and code. Is the method/code only applicable for llama or can it be used with any autoregressive model? If it's the latter,  are there instructions on how to quantize the kvcache of an arbitrary transformer model?

**Comment by zirui-ray-liu** [comment]
Thank you for interesting in our work. Yes, it can be applied to any autoregressive model!

You can think KiVi as another implementation of KVCache. You can copy-paste the [code](https://github.com/jy-yuan/KIVI/blob/main/models/llama_kivi.py#L19) here and modify it for the attention module in different models like [MistralAttention](https://github.com/huggingface/transformers/blob/main/src/transformers/models/mistral/modeling_mistral.py#L195).

Here we would like to note two important things we found when we extend KiVi to different models. 

1. **Transformer Package Version**: Please double check the transformer package version. We test our implementation in 4.35.2. Yet in version >= 4.36, the KVCache data structure is changed. 

2. **Attention Implementation Variants**: Please double check what is the attention mechanism used in the model (Multi-Head/Multi-Query/Group-Query). Currently we only release the CUDA and triton code for supporting Multi-Head Attention. For Multi-Query/Group-Query,  it needs to change the low-level implementation a little bit. We will release this part soon.

Stay tuned for further developments!
