### ISSUE TITLE
Which file I need to run to obtain the result in Figure 4？

### ISSUE THREAD

**Issue by Felixvillas** [jy-yuan/KIVI#11]
I want to test the memory usage andt hroughput comparison between 2bit KIVI and 16 bit baseline.  How can I test them?

**Comment by jy-yuan** [comment]
Please refer to [mem_spd_test.py](https://github.com/jy-yuan/KIVI/blob/main/mem_spd_test.py)

**Comment by Felixvillas** [comment]
> Please refer to [mem_spd_test.py](https://github.com/jy-yuan/KIVI/blob/main/mem_spd_test.py)

thank you, I'll try it!
