### ISSUE TITLE
Where is the falcon_kivi?

### ISSUE THREAD

**Issue by Felixvillas** [jy-yuan/KIVI#14]
Due to table7 in paper, the experiments of llama, falcon and mistral are tested, but there are only [llama_kivi.py](https://github.com/jy-yuan/KIVI/blob/main/models/llama_kivi.py) and [mistral_kivi.py](https://github.com/jy-yuan/KIVI/blob/main/models/mistral_kivi.py) but no falcon.py in https://github.com/jy-yuan/KIVI/tree/main/models.
How can I get it?

**Comment by Felixvillas** [comment]
And where are `models/modeling_mistral.py`, `models/mistral_kivi.py`, `models/modeling_falcon.py` and `models/falcon_kivi.py` in the branch lmeval?

**Comment by zirui-ray-liu** [comment]
Thank you for your interests! I will collaborate with @jy-yuan to release these code and falcon version soon.

**Comment by jy-yuan** [comment]
Hi, @Felixvillas; thanks for your patience; we have updated the corresponding mistral and falcon files to the branch lmeval.

**Comment by Felixvillas** [comment]
> Hi, @Felixvillas; thanks for your patience; we have updated the corresponding mistral and falcon files to the branch lmeval.

Thank you, I'll try it!
