### ISSUE TITLE
CUDA version

### ISSUE THREAD

**Issue by hensiesp32** [jy-yuan/KIVI#16]
Thanks for your wonderful work. I have a question about the cuda version, does is only support cuda 12.*? My computer is cuda 11.8, but i met some trouble with the conda enviroment. wish your reply.

**Comment by zirui-ray-liu** [comment]
Thank you for your interest! We previously tested with > cuda 12.0. Can you copy paste the error message with cuda 11.8? I will double check.

**Comment by hensiesp32** [comment]
Sure.  When I executed this command ”cd quant && pip install -e .“ , the following error occurred
![image](https://github.com/jy-yuan/KIVI/assets/83627510/6741fc97-f0a6-41ea-8372-79a09d87d756)

And my computer cuda setting is 
![image](https://github.com/jy-yuan/KIVI/assets/83627510/f13c9a37-56bf-4439-ae07-b17fdc32dd78)
 
And the pip list :
``` 
accelerate               0.25.0
asttokens                2.4.1
attributedict            0.3.0
blessings                1.7
cachetools               5.3.3
certifi                  2024.2.2
chardet                  5.2.0
charset-normalizer       3.3.2
codecov                  2.1.13
colorama                 0.4.6
coloredlogs              15.0.1
colour-runner            0.1.1
coverage                 7.5.1
decorator                5.1.1
deepdiff                 7.0.1
distlib                  0.3.8
exceptiongroup           1.2.1
executing                2.0.1
fastchat                 0.1.0
filelock                 3.14.0
fsspec                   2024.3.1
huggingface-hub          0.23.0
humanfriendly            10.0
idna                     3.7
inspecta                 0.1.3
ipdb                     0.13.13
ipython                  8.24.0
jedi                     0.19.1
Jinja2                   3.1.4
kivi                     0.1.0       
MarkupSafe               2.1.5
matplotlib-inline        0.1.7
mpmath                   1.3.0
networkx                 3.3
numpy                    1.26.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.18.1
nvidia-nvjitlink-cu12    12.4.127
nvidia-nvtx-cu12         12.1.105
ordered-set              4.1.0
packaging                24.0
parso                    0.8.4
pexpect                  4.9.0
pillow                   10.2.0
pip                      24.0
platformdirs             4.2.1
pluggy                   1.5.0
prompt-toolkit           3.0.43
protobuf                 5.26.1
psutil                   5.9.8
ptyprocess               0.7.0
pure-eval                0.2.2
Pygments                 2.18.0
pyproject-api            1.6.1
PyYAML                   6.0.1
regex                    2024.5.10
requests                 2.31.0
rootpath                 0.1.1
safetensors              0.4.3
sentencepiece            0.2.0
setuptools               69.5.1
six                      1.16.0
stack-data               0.6.3
sympy                    1.12
termcolor                2.4.0
tokenizers               0.15.2
toml                     0.10.2
tomli                    2.0.1
torch                    2.1.2
torchaudio               2.1.2+cu118
torchvision              0.16.2+cu118
tox                      4.15.0
tqdm                     4.66.4
traitlets                5.14.3
transformers             4.36.2
triton                   2.1.0
typing_extensions        4.11.0
urllib3                  2.2.1
virtualenv               20.26.2
wcwidth                  0.2.13
wheel                    0.43.0
```

**Comment by hensiesp32** [comment]
> Sure. When I executed this command ”cd quant && pip install -e .“ , the following error occurred ![image](https://private-user-images.githubusercontent.com/83627510/331019255-6741fc97-f0a6-41ea-8372-79a09d87d756.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjU5NTQsIm5iZiI6MTcxNTgyNTY1NCwicGF0aCI6Ii84MzYyNzUxMC8zMzEwMTkyNTUtNjc0MWZjOTctZjBhNi00MWVhLTgzNzItNzlhMDlkODdkNzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAyMTQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2YzBmNDA1YzAxMGU5NjQ2YTcxNWZjZmMxOTQyODNjNjFlZWVjYjM2MjQ0NTIzM2FhZDU1ZmU2MmYzNDE1ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._OP5-4fk1ofoGpQYvids7TntAAydX_ND3XUHvdrnpnw)
> 
> And my computer cuda setting is ![image](https://private-user-images.githubusercontent.com/83627510/331019702-f13c9a37-56bf-4439-ae07-b17fdc32dd78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjU5NTQsIm5iZiI6MTcxNTgyNTY1NCwicGF0aCI6Ii84MzYyNzUxMC8zMzEwMTk3MDItZjEzYzlhMzctNTZiZi00NDM5LWFlMDctYjE3ZmRjMzJkZDc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAyMTQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5OWE4N2QyMzVkN2I2OTRmYzJiZDc3NWVlNzk1MDMxNTQyNjViM2RlNjU3M2Q0NDc2ODljZjZiOWIxMmI1ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X7evjPJ_d6szmJ6x5gmaktOaHLF1KasyUlZ-umwLeR0)
> 
> And the pip list :
> 
> ```
> accelerate               0.25.0
> asttokens                2.4.1
> attributedict            0.3.0
> blessings                1.7
> cachetools               5.3.3
> certifi                  2024.2.2
> chardet                  5.2.0
> charset-normalizer       3.3.2
> codecov                  2.1.13
> colorama                 0.4.6
> coloredlogs              15.0.1
> colour-runner            0.1.1
> coverage                 7.5.1
> decorator                5.1.1
> deepdiff                 7.0.1
> distlib                  0.3.8
> exceptiongroup           1.2.1
> executing                2.0.1
> fastchat                 0.1.0
> filelock                 3.14.0
> fsspec                   2024.3.1
> huggingface-hub          0.23.0
> humanfriendly            10.0
> idna                     3.7
> inspecta                 0.1.3
> ipdb                     0.13.13
> ipython                  8.24.0
> jedi                     0.19.1
> Jinja2                   3.1.4
> kivi                     0.1.0       
> MarkupSafe               2.1.5
> matplotlib-inline        0.1.7
> mpmath                   1.3.0
> networkx                 3.3
> numpy                    1.26.4
> nvidia-cublas-cu12       12.1.3.1
> nvidia-cuda-cupti-cu12   12.1.105
> nvidia-cuda-nvrtc-cu12   12.1.105
> nvidia-cuda-runtime-cu12 12.1.105
> nvidia-cudnn-cu12        8.9.2.26
> nvidia-cufft-cu12        11.0.2.54
> nvidia-curand-cu12       10.3.2.106
> nvidia-cusolver-cu12     11.4.5.107
> nvidia-cusparse-cu12     12.1.0.106
> nvidia-nccl-cu12         2.18.1
> nvidia-nvjitlink-cu12    12.4.127
> nvidia-nvtx-cu12         12.1.105
> ordered-set              4.1.0
> packaging                24.0
> parso                    0.8.4
> pexpect                  4.9.0
> pillow                   10.2.0
> pip                      24.0
> platformdirs             4.2.1
> pluggy                   1.5.0
> prompt-toolkit           3.0.43
> protobuf                 5.26.1
> psutil                   5.9.8
> ptyprocess               0.7.0
> pure-eval                0.2.2
> Pygments                 2.18.0
> pyproject-api            1.6.1
> PyYAML                   6.0.1
> regex                    2024.5.10
> requests                 2.31.0
> rootpath                 0.1.1
> safetensors              0.4.3
> sentencepiece            0.2.0
> setuptools               69.5.1
> six                      1.16.0
> stack-data               0.6.3
> sympy                    1.12
> termcolor                2.4.0
> tokenizers               0.15.2
> toml                     0.10.2
> tomli                    2.0.1
> torch                    2.1.2
> torchaudio               2.1.2+cu118
> torchvision              0.16.2+cu118
> tox                      4.15.0
> tqdm                     4.66.4
> traitlets                5.14.3
> transformers             4.36.2
> triton                   2.1.0
> typing_extensions        4.11.0
> urllib3                  2.2.1
> virtualenv               20.26.2
> wcwidth                  0.2.13
> wheel                    0.43.0
> ```

**Comment by hensiesp32** [comment]
> Thank you for your interest! We previously tested with > cuda 12.0. Can you copy paste the error message with cuda 11.8? I will double check.

Sure.  When I executed this command ”cd quant && pip install -e .“ , the following error occurred
![image](https://github.com/jy-yuan/KIVI/assets/83627510/6741fc97-f0a6-41ea-8372-79a09d87d756)

And my computer cuda setting is 
![image](https://github.com/jy-yuan/KIVI/assets/83627510/f13c9a37-56bf-4439-ae07-b17fdc32dd78)
 
And the pip list :
``` 
accelerate               0.25.0
asttokens                2.4.1
attributedict            0.3.0
blessings                1.7
cachetools               5.3.3
certifi                  2024.2.2
chardet                  5.2.0
charset-normalizer       3.3.2
codecov                  2.1.13
colorama                 0.4.6
coloredlogs              15.0.1
colour-runner            0.1.1
coverage                 7.5.1
decorator                5.1.1
deepdiff                 7.0.1
distlib                  0.3.8
exceptiongroup           1.2.1
executing                2.0.1
fastchat                 0.1.0
filelock                 3.14.0
fsspec                   2024.3.1
huggingface-hub          0.23.0
humanfriendly            10.0
idna                     3.7
inspecta                 0.1.3
ipdb                     0.13.13
ipython                  8.24.0
jedi                     0.19.1
Jinja2                   3.1.4
kivi                     0.1.0       
MarkupSafe               2.1.5
matplotlib-inline        0.1.7
mpmath                   1.3.0
networkx                 3.3
numpy                    1.26.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.18.1
nvidia-nvjitlink-cu12    12.4.127
nvidia-nvtx-cu12         12.1.105
ordered-set              4.1.0
packaging                24.0
parso                    0.8.4
pexpect                  4.9.0
pillow                   10.2.0
pip                      24.0
platformdirs             4.2.1
pluggy                   1.5.0
prompt-toolkit           3.0.43
protobuf                 5.26.1
psutil                   5.9.8
ptyprocess               0.7.0
pure-eval                0.2.2
Pygments                 2.18.0
pyproject-api            1.6.1
PyYAML                   6.0.1
regex                    2024.5.10
requests                 2.31.0
rootpath                 0.1.1
safetensors              0.4.3
sentencepiece            0.2.0
setuptools               69.5.1
six                      1.16.0
stack-data               0.6.3
sympy                    1.12
termcolor                2.4.0
tokenizers               0.15.2
toml                     0.10.2
tomli                    2.0.1
torch                    2.1.2
torchaudio               2.1.2+cu118
torchvision              0.16.2+cu118
tox                      4.15.0
tqdm                     4.66.4
traitlets                5.14.3
transformers             4.36.2
triton                   2.1.0
typing_extensions        4.11.0
urllib3                  2.2.1
virtualenv               20.26.2
wcwidth                  0.2.13
wheel                    0.43.0
```

**Comment by hensiesp32** [comment]
> Thank you for your interest! We previously tested with > cuda 12.0. Can you copy paste the error message with cuda 11.8? I will double check.

One of my questions is which version of the following tool libraries associated with CUDA should i install to match the cuda11.8
```
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.18.1
nvidia-nvjitlink-cu12    12.4.127
nvidia-nvtx-cu12         12.1.105
```

**Comment by henryzhongsc** [comment]
Unfortunately, this is a question we cannot answer with confidence because our server is currently running on CUDA 12+, and it is non-trivial to downgrade our driver to figure out a CUDA 11.8-compatible environment that supports KIVI.

We recommend picking a cu118-compatible torch release, installing the transformers lib as stipulated, then running the code and resolving each dependency error one by one. Likely none of the cuda-related dependencies you pasted above is compatible with CUDA 11.8 as they all have cu12 in their names. Your best shot is to seek out an alternative cu118-based environment that supports KIVI.
