### ISSUE TITLE
Could you please open-source the code for the calculation and visualization of the statistic information of KV Cache?

### ISSUE THREAD

**Issue by wln20** [jy-yuan/KIVI#2]
It's really pleasant to discover such a nice work! Could you please further provide the code to calculate and visualize the statistic information of KV Cache (like the following image), so it would be easy for future researchers to observe the pattern of KV Cache on more new models? Thanks a lot!
![2024-03-05_130540](https://github.com/jy-yuan/KIVI/assets/79293837/b5cc8d82-2820-4983-89b8-82938cd33fcc)

**Comment by jy-yuan** [comment]
We have added the visualization code along with instructions to [vis.ipynb](https://github.com/jy-yuan/KIVI/blob/main/vis/vis.ipynb). Thank you for bringing this to our attention!

**Comment by wln20** [comment]
Thanks for your attention! By the way, I got some trouble when using `pip install -r requirements.txt` to install the dependencies: 
![image](https://github.com/jy-yuan/KIVI/assets/79293837/66873e0a-0ca5-4409-b1c7-62c1292ad9c6). It seems to be a problem concerning `==` and `=`. Could you help fix it?

**Comment by jy-yuan** [comment]
Apologies for the error. We used conda to export the requirements and have since updated the README.
