### ISSUE TITLE
NameError: name 'flash_attn_func' is not defined

### ISSUE THREAD

**Issue by zwhong714** [jy-yuan/KIVI#20]
When I execute the command python long_context_example.py, I encounter the following error: NameError: name 'flash_attn_func' is not defined.

**Comment by zirui-ray-liu** [comment]
> I encounter the following error: NameError: name 'flash_attn_func' is not defined.

I can run it on my server. What is your transformer and flash-attn version? Did you follow the instruction in "Setup" of README?
