### ISSUE TITLE
Difference between gemv_forward_cuda and gemv_forward_cuda_outer_rim?

### ISSUE THREAD

**Issue by yifeikong** [jy-yuan/KIVI#22]
I also notice that gemv_forward_cuda is not used anywhere in the benchmark code.

**Comment by zirui-ray-liu** [comment]
Thank you for your interests.

"gemv_forward_cuda" is the API for fused matmul between full precison matrix A and an integer matrix B quantized along the inner dim. For example, if A is a FP16 matrix of shape [M, K], B is an integer matrix of shape [K, N]. "gemv_forward_cuda"  requires quantizing B along the dimension "K". 

In contrast, "gemv_forward_cuda_outer_dim" requires quantizing B along the dimension "N". 

In KIVI, all fused matmul is implemented through "gemv_forward_cuda_outer_dim".

**Comment by yifeikong** [comment]
Thanks, well explained.
