### ISSUE TITLE
How to understand the code: triton_quantize_and_pack_along_last_dim(value_states_full[:, :, :1, :].contiguous(), self.group_size, self.v_bits)

### ISSUE THREAD

**Issue by chenyehuang** [jy-yuan/KIVI#23]
![微信截图_20240624190119](https://github.com/jy-yuan/KIVI/assets/88588202/f87a942a-484b-4cba-93a7-f01b75e61c21)

I don't understand why the input data is value_states_full[:, :, :1, :].contiguous() instead of value_states_full[:, :, :-1, :].transpose(2, 3).contiguous()

**Comment by zirui-ray-liu** [comment]
Thank you for your interests.

The "value_states_quant_new" is the quantized oldest token that currently outside the full precision sliding window. The code piece means when the sliding window is full and a new token arrive, we pop and quantize the oldest token. For more details, please check the [Algorithm 1](https://arxiv.org/pdf/2402.02750) in our paper.

**Comment by chenyehuang** [comment]
Thanks for your answer.
I reread the paper and found my idea was wrong because value is per-token quantization. 
The dimension of value_states_full[:, :, :1, :] is [B,nh,1,D], but the dimension is not converted in the function triton_quantize_and_pack_along_last_dim, and D is used instead of T. If I use other models that are not llama, do I also need to make sure that D is divisible by group_size?
![微信截图_20240625105735](https://github.com/jy-yuan/KIVI/assets/88588202/8bdbe70f-202d-452b-88fc-c3bdbf6f7bd8)

**Comment by zirui-ray-liu** [comment]
for value cache, "T" in this code piece means the head_dim. Usually speaking, the head_dim is either 128/256. Commonly used group size 32/64/128 are fully compatible with almost all LLMs.
